/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
*/

#include<iostream>
#include<vector>
#define ll long long
using namespace std;
vector<ll>mem;
ll limit = 4000000;
ll solve(long long n){
    mem[0] = 0;
    mem[1] = 1;
    ll res = 0;
    for(int i=0;i<mem.size()-2;i++){
        if(mem[i]>limit) break;
        res += mem[i]%2==0?mem[i]:0;
        mem[i+1] += mem[i];
        mem[i+2] += mem[i];
    }
    return res;
}

int main(){
    int n;
    cin>>n;
    mem.resize(100,0);
    cout<<"Maximum limit is 4 million: (n=25)\n";
    cout<<solve(n)<<endl;
    return 0;
}